services:
  postgresql-tasks:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
  
  rabbitmq:
    environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=password
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  
  rustfs:
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - rustfs_data:/data
      - rustfs_logs:/logs
    environment:
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
      - RUSTFS_CONSOLE_ENABLE=true

    image: rustfs/rustfs:latest

volumes:
  rustfs_data:
  rustfs_logs: