include:
  - docker-compose.phoenix.yml

services:
  ollama:
    build: ./ollama
    volumes:
      - ollama_data:/root/.ollama
    env_file: ".env"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  server:
    build:
      context: ./backend
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file: ".env"
    depends_on:
      ollama:
        condition: service_started
      alloy:
        condition: service_started


  ui:
    build:
      context: frontend
    ports:
      - "8070:8070"
    env_file: ".env"
    depends_on:
        - server
  
  prometheus:
    build: ./Prometheus
    ports:
      - "9090:9090"
  
volumes:
  ollama_data:


