services:
  ollama:
    build: ./ollama
    volumes:
      - ollama_data:/root/.ollama
    env_file: ".env"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  server:
    build:
      context: ./backend
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file: ".env"
    depends_on:
      ollama:
        condition: service_started
      alloy:
        condition: service_started


  ui:
    build:
      context: frontend
    ports:
      - "8070:8070"
    env_file: ".env"
    depends_on:
        - server
  
  prometheus:
    build: ./Prometheus
    ports:
      - "9090:9090"
  
  grafana:
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    image: grafana/grafana-oss

  alloy:
    build: ./alloy
    ports:
      - "12345:12345"
    depends_on:
      - prometheus
  
  postgresql:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langfuse"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: langfuse
      POSTGRES_DB: langfuse


volumes:
  weaviate_data:
  ollama_data:
  embed_data:


